# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateUsers.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(890, 607)
        self.tabWidget_2 = QtWidgets.QTabWidget(Form)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 1171, 821))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.txtQuerie = QtWidgets.QTextEdit(self.tab_6)
        self.txtQuerie.setGeometry(QtCore.QRect(330, 450, 291, 31))
        self.txtQuerie.setObjectName("txtQuerie")
        self.pbCheckALLUser = QtWidgets.QPushButton(self.tab_6)
        self.pbCheckALLUser.setGeometry(QtCore.QRect(20, 530, 221, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbCheckALLUser.setFont(font)
        self.pbCheckALLUser.setObjectName("pbCheckALLUser")
        self.pbInserirTexto = QtWidgets.QPushButton(self.tab_6)
        self.pbInserirTexto.setGeometry(QtCore.QRect(690, 500, 181, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbInserirTexto.setFont(font)
        self.pbInserirTexto.setObjectName("pbInserirTexto")
        self.pbLoadingData = QtWidgets.QPushButton(self.tab_6)
        self.pbLoadingData.setGeometry(QtCore.QRect(690, 420, 181, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbLoadingData.setFont(font)
        self.pbLoadingData.setObjectName("pbLoadingData")
        self.pbDownloadSAPUsers = QtWidgets.QPushButton(self.tab_6)
        self.pbDownloadSAPUsers.setGeometry(QtCore.QRect(690, 380, 181, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbDownloadSAPUsers.setFont(font)
        self.pbDownloadSAPUsers.setObjectName("pbDownloadSAPUsers")
        self.pbValidateRecord = QtWidgets.QPushButton(self.tab_6)
        self.pbValidateRecord.setGeometry(QtCore.QRect(690, 340, 181, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbValidateRecord.setFont(font)
        self.pbValidateRecord.setObjectName("pbValidateRecord")
        self.pbCreateUser = QtWidgets.QPushButton(self.tab_6)
        self.pbCreateUser.setGeometry(QtCore.QRect(690, 300, 181, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbCreateUser.setFont(font)
        self.pbCreateUser.setObjectName("pbCreateUser")
        self.cbUserExisted = QtWidgets.QCheckBox(self.tab_6)
        self.cbUserExisted.setGeometry(QtCore.QRect(700, 280, 121, 17))
        self.cbUserExisted.setObjectName("cbUserExisted")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_6)
        self.tabWidget.setGeometry(QtCore.QRect(10, 260, 681, 161))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 0, 261, 141))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_27.setObjectName("label_27")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.txtRole01 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.txtRole01.setObjectName("txtRole01")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtRole01)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_28.setObjectName("label_28")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.txtRole02 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.txtRole02.setObjectName("txtRole02")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtRole02)
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_29.setObjectName("label_29")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.txtRole03 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.txtRole03.setObjectName("txtRole03")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtRole03)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_30.setObjectName("label_30")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.txtRole04 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.txtRole04.setObjectName("txtRole04")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtRole04)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_31.setObjectName("label_31")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.txtRole05 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.txtRole05.setObjectName("txtRole05")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtRole05)
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(320, 0, 261, 141))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_32 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_32.setObjectName("label_32")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_33.setObjectName("label_33")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.label_34 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_34.setObjectName("label_34")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.label_35 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_35.setObjectName("label_35")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.label_36 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_36.setObjectName("label_36")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.txtRole06 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.txtRole06.setObjectName("txtRole06")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtRole06)
        self.txtRole07 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.txtRole07.setObjectName("txtRole07")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtRole07)
        self.txtRole08 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.txtRole08.setObjectName("txtRole08")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtRole08)
        self.txtRole09 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.txtRole09.setObjectName("txtRole09")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtRole09)
        self.txtRole10 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.txtRole10.setObjectName("txtRole10")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtRole10)
        self.pbCK01 = QtWidgets.QPushButton(self.tab)
        self.pbCK01.setGeometry(QtCore.QRect(280, 0, 21, 23))
        self.pbCK01.setObjectName("pbCK01")
        self.pbCK02 = QtWidgets.QPushButton(self.tab)
        self.pbCK02.setGeometry(QtCore.QRect(280, 25, 21, 23))
        self.pbCK02.setObjectName("pbCK02")
        self.pbCK03 = QtWidgets.QPushButton(self.tab)
        self.pbCK03.setGeometry(QtCore.QRect(280, 50, 21, 23))
        self.pbCK03.setObjectName("pbCK03")
        self.pbCK04 = QtWidgets.QPushButton(self.tab)
        self.pbCK04.setGeometry(QtCore.QRect(280, 76, 21, 23))
        self.pbCK04.setObjectName("pbCK04")
        self.pbCK05 = QtWidgets.QPushButton(self.tab)
        self.pbCK05.setGeometry(QtCore.QRect(280, 102, 21, 23))
        self.pbCK05.setObjectName("pbCK05")
        self.pbCK06 = QtWidgets.QPushButton(self.tab)
        self.pbCK06.setGeometry(QtCore.QRect(590, -1, 21, 23))
        self.pbCK06.setObjectName("pbCK06")
        self.pbCK07 = QtWidgets.QPushButton(self.tab)
        self.pbCK07.setGeometry(QtCore.QRect(590, 25, 21, 23))
        self.pbCK07.setObjectName("pbCK07")
        self.pbCK08 = QtWidgets.QPushButton(self.tab)
        self.pbCK08.setGeometry(QtCore.QRect(590, 52, 21, 23))
        self.pbCK08.setObjectName("pbCK08")
        self.pbCK09 = QtWidgets.QPushButton(self.tab)
        self.pbCK09.setGeometry(QtCore.QRect(590, 78, 21, 23))
        self.pbCK09.setObjectName("pbCK09")
        self.pbCK10 = QtWidgets.QPushButton(self.tab)
        self.pbCK10.setGeometry(QtCore.QRect(590, 103, 21, 23))
        self.pbCK10.setObjectName("pbCK10")
        self.pbNumber = QtWidgets.QLabel(self.tab)
        self.pbNumber.setGeometry(QtCore.QRect(620, 30, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pbNumber.setFont(font)
        self.pbNumber.setFrameShape(QtWidgets.QFrame.Box)
        self.pbNumber.setText("")
        self.pbNumber.setObjectName("pbNumber")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(10, 0, 261, 161))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_37 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_37.setObjectName("label_37")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_38.setObjectName("label_38")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.label_39 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_39.setObjectName("label_39")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.label_40 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_40.setObjectName("label_40")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.label_41 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_41.setObjectName("label_41")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.txtRole11 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.txtRole11.setObjectName("txtRole11")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtRole11)
        self.txtRole12 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.txtRole12.setObjectName("txtRole12")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtRole12)
        self.txtRole13 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.txtRole13.setObjectName("txtRole13")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtRole13)
        self.txtRole14 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.txtRole14.setObjectName("txtRole14")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtRole14)
        self.txtRole15 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.txtRole15.setObjectName("txtRole15")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtRole15)
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(320, 0, 261, 161))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_42 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_42.setObjectName("label_42")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.label_43 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_43.setObjectName("label_43")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.label_44 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_44.setObjectName("label_44")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.label_45 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_45.setObjectName("label_45")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.label_46 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_46.setObjectName("label_46")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.txtRole16 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.txtRole16.setObjectName("txtRole16")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtRole16)
        self.txtRole17 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.txtRole17.setObjectName("txtRole17")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtRole17)
        self.txtRole18 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.txtRole18.setObjectName("txtRole18")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtRole18)
        self.txtRole19 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.txtRole19.setObjectName("txtRole19")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtRole19)
        self.txtRole20 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.txtRole20.setObjectName("txtRole20")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtRole20)
        self.pbCK12 = QtWidgets.QPushButton(self.tab_2)
        self.pbCK12.setGeometry(QtCore.QRect(280, 25, 21, 23))
        self.pbCK12.setObjectName("pbCK12")
        self.pbCK13 = QtWidgets.QPushButton(self.tab_2)
        self.pbCK13.setGeometry(QtCore.QRect(280, 50, 21, 23))
        self.pbCK13.setObjectName("pbCK13")
        self.pbCK14 = QtWidgets.QPushButton(self.tab_2)
        self.pbCK14.setGeometry(QtCore.QRect(280, 76, 21, 23))
        self.pbCK14.setObjectName("pbCK14")
        self.pbCK15 = QtWidgets.QPushButton(self.tab_2)
        self.pbCK15.setGeometry(QtCore.QRect(280, 102, 21, 23))
        self.pbCK15.setObjectName("pbCK15")
        self.pbCK11 = QtWidgets.QPushButton(self.tab_2)
        self.pbCK11.setGeometry(QtCore.QRect(280, 0, 21, 23))
        self.pbCK11.setObjectName("pbCK11")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_17.setGeometry(QtCore.QRect(590, 78, 21, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_18.setGeometry(QtCore.QRect(590, 103, 21, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_19.setGeometry(QtCore.QRect(590, -1, 21, 23))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_20.setGeometry(QtCore.QRect(590, 52, 21, 23))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_21.setGeometry(QtCore.QRect(590, 25, 21, 23))
        self.pushButton_21.setObjectName("pushButton_21")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget_9 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(10, 0, 261, 161))
        self.formLayoutWidget_9.setObjectName("formLayoutWidget_9")
        self.formLayout_9 = QtWidgets.QFormLayout(self.formLayoutWidget_9)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_47 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_47.setObjectName("label_47")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.label_48 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_48.setObjectName("label_48")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.label_49 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_49.setObjectName("label_49")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.label_50 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_50.setObjectName("label_50")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_50)
        self.label_51 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_51.setObjectName("label_51")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.txtRole21 = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.txtRole21.setObjectName("txtRole21")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtRole21)
        self.txtRole22 = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.txtRole22.setObjectName("txtRole22")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtRole22)
        self.txtRole23 = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.txtRole23.setObjectName("txtRole23")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtRole23)
        self.txtRole24 = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.txtRole24.setObjectName("txtRole24")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtRole24)
        self.txtRole25 = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.txtRole25.setObjectName("txtRole25")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtRole25)
        self.formLayoutWidget_10 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_10.setGeometry(QtCore.QRect(320, 0, 271, 161))
        self.formLayoutWidget_10.setObjectName("formLayoutWidget_10")
        self.formLayout_10 = QtWidgets.QFormLayout(self.formLayoutWidget_10)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_52 = QtWidgets.QLabel(self.formLayoutWidget_10)
        self.label_52.setObjectName("label_52")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_52)
        self.label_53 = QtWidgets.QLabel(self.formLayoutWidget_10)
        self.label_53.setObjectName("label_53")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.label_54 = QtWidgets.QLabel(self.formLayoutWidget_10)
        self.label_54.setObjectName("label_54")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.label_55 = QtWidgets.QLabel(self.formLayoutWidget_10)
        self.label_55.setObjectName("label_55")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_55)
        self.label_56 = QtWidgets.QLabel(self.formLayoutWidget_10)
        self.label_56.setObjectName("label_56")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.txtRole26 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.txtRole26.setObjectName("txtRole26")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtRole26)
        self.txtRole27 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.txtRole27.setObjectName("txtRole27")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtRole27)
        self.txtRole28 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.txtRole28.setObjectName("txtRole28")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtRole28)
        self.txtRole29 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.txtRole29.setObjectName("txtRole29")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtRole29)
        self.txtRole30 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.txtRole30.setObjectName("txtRole30")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtRole30)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget_11 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_11.setGeometry(QtCore.QRect(10, 0, 261, 161))
        self.formLayoutWidget_11.setObjectName("formLayoutWidget_11")
        self.formLayout_11 = QtWidgets.QFormLayout(self.formLayoutWidget_11)
        self.formLayout_11.setContentsMargins(0, 0, 0, 0)
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_57 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.label_57.setObjectName("label_57")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_57)
        self.label_58 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.label_58.setObjectName("label_58")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_58)
        self.label_59 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.label_59.setObjectName("label_59")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_59)
        self.label_60 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.label_60.setObjectName("label_60")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_60)
        self.label_61 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.label_61.setObjectName("label_61")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_61)
        self.txtRole31 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.txtRole31.setObjectName("txtRole31")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtRole31)
        self.txtRole32 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.txtRole32.setObjectName("txtRole32")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtRole32)
        self.txtRole33 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.txtRole33.setObjectName("txtRole33")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtRole33)
        self.txtRole34 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.txtRole34.setObjectName("txtRole34")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtRole34)
        self.txtRole35 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.txtRole35.setObjectName("txtRole35")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtRole35)
        self.formLayoutWidget_12 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_12.setGeometry(QtCore.QRect(320, 0, 271, 161))
        self.formLayoutWidget_12.setObjectName("formLayoutWidget_12")
        self.formLayout_12 = QtWidgets.QFormLayout(self.formLayoutWidget_12)
        self.formLayout_12.setContentsMargins(0, 0, 0, 0)
        self.formLayout_12.setObjectName("formLayout_12")
        self.label_62 = QtWidgets.QLabel(self.formLayoutWidget_12)
        self.label_62.setObjectName("label_62")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_62)
        self.label_63 = QtWidgets.QLabel(self.formLayoutWidget_12)
        self.label_63.setObjectName("label_63")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_63)
        self.label_64 = QtWidgets.QLabel(self.formLayoutWidget_12)
        self.label_64.setObjectName("label_64")
        self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.label_65 = QtWidgets.QLabel(self.formLayoutWidget_12)
        self.label_65.setObjectName("label_65")
        self.formLayout_12.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_65)
        self.label_66 = QtWidgets.QLabel(self.formLayoutWidget_12)
        self.label_66.setObjectName("label_66")
        self.formLayout_12.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_66)
        self.txtRole36 = QtWidgets.QLineEdit(self.formLayoutWidget_12)
        self.txtRole36.setObjectName("txtRole36")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtRole36)
        self.txtRole37 = QtWidgets.QLineEdit(self.formLayoutWidget_12)
        self.txtRole37.setObjectName("txtRole37")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtRole37)
        self.txtRole38 = QtWidgets.QLineEdit(self.formLayoutWidget_12)
        self.txtRole38.setObjectName("txtRole38")
        self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtRole38)
        self.txtRole39 = QtWidgets.QLineEdit(self.formLayoutWidget_12)
        self.txtRole39.setObjectName("txtRole39")
        self.formLayout_12.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtRole39)
        self.txtRole40 = QtWidgets.QLineEdit(self.formLayoutWidget_12)
        self.txtRole40.setObjectName("txtRole40")
        self.formLayout_12.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtRole40)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_5)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 0, 261, 161))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.txtRole41 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.txtRole41.setObjectName("txtRole41")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtRole41)
        self.txtRole42 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.txtRole42.setObjectName("txtRole42")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtRole42)
        self.txtRole43 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.txtRole43.setObjectName("txtRole43")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtRole43)
        self.txtRole44 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.txtRole44.setObjectName("txtRole44")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtRole44)
        self.txtRole45 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.txtRole45.setObjectName("txtRole45")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtRole45)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_5)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(320, 0, 271, 161))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_22.setObjectName("label_22")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_23.setObjectName("label_23")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_24.setObjectName("label_24")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.txtRole46 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.txtRole46.setObjectName("txtRole46")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtRole46)
        self.txtRole47 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.txtRole47.setObjectName("txtRole47")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtRole47)
        self.txtRole48 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.txtRole48.setObjectName("txtRole48")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtRole48)
        self.txtRole49 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.txtRole49.setObjectName("txtRole49")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtRole49)
        self.txtRole50 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.txtRole50.setObjectName("txtRole50")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtRole50)
        self.tabWidget.addTab(self.tab_5, "")
        self.pbExceptional2 = QtWidgets.QPushButton(self.tab_6)
        self.pbExceptional2.setGeometry(QtCore.QRect(290, 504, 21, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.pbExceptional2.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbExceptional2.setFont(font)
        self.pbExceptional2.setAutoFillBackground(False)
        self.pbExceptional2.setStyleSheet("")
        self.pbExceptional2.setObjectName("pbExceptional2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_6)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 425, 261, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.txtexceptional2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtexceptional2.setObjectName("txtexceptional2")
        self.gridLayout.addWidget(self.txtexceptional2, 3, 0, 1, 1)
        self.txtexceptional1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtexceptional1.setObjectName("txtexceptional1")
        self.gridLayout.addWidget(self.txtexceptional1, 2, 0, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_67.setObjectName("label_67")
        self.gridLayout.addWidget(self.label_67, 0, 0, 1, 1)
        self.txtexceptional = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtexceptional.setAutoFillBackground(False)
        self.txtexceptional.setObjectName("txtexceptional")
        self.gridLayout.addWidget(self.txtexceptional, 1, 0, 1, 1)
        self.pbExceptional1 = QtWidgets.QPushButton(self.tab_6)
        self.pbExceptional1.setGeometry(QtCore.QRect(290, 477, 21, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbExceptional1.setFont(font)
        self.pbExceptional1.setObjectName("pbExceptional1")
        self.pbExceptional = QtWidgets.QPushButton(self.tab_6)
        self.pbExceptional.setGeometry(QtCore.QRect(290, 450, 21, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbExceptional.setFont(font)
        self.pbExceptional.setObjectName("pbExceptional")
        self.groupBox = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox.setGeometry(QtCore.QRect(0, 210, 311, 41))
        self.groupBox.setObjectName("groupBox")
        self.rbN1 = QtWidgets.QRadioButton(self.groupBox)
        self.rbN1.setGeometry(QtCore.QRect(10, 20, 51, 22))
        self.rbN1.setObjectName("rbN1")
        self.rbN2 = QtWidgets.QRadioButton(self.groupBox)
        self.rbN2.setGeometry(QtCore.QRect(60, 20, 51, 22))
        self.rbN2.setObjectName("rbN2")
        self.rbN3 = QtWidgets.QRadioButton(self.groupBox)
        self.rbN3.setGeometry(QtCore.QRect(120, 20, 51, 22))
        self.rbN3.setObjectName("rbN3")
        self.rbN4 = QtWidgets.QRadioButton(self.groupBox)
        self.rbN4.setGeometry(QtCore.QRect(170, 20, 51, 22))
        self.rbN4.setObjectName("rbN4")
        self.rbN5 = QtWidgets.QRadioButton(self.groupBox)
        self.rbN5.setGeometry(QtCore.QRect(220, 20, 51, 22))
        self.rbN5.setObjectName("rbN5")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_6)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 0, 311, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtrequestId = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtrequestId.setObjectName("txtrequestId")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtrequestId)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtsystemType = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtsystemType.setObjectName("txtsystemType")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtsystemType)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtsystemEnv = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtsystemEnv.setAutoFillBackground(False)
        self.txtsystemEnv.setObjectName("txtsystemEnv")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtsystemEnv)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtgroup = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtgroup.setObjectName("txtgroup")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtgroup)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txtsncName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtsncName.setObjectName("txtsncName")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtsncName)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.txtlanguage = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtlanguage.setObjectName("txtlanguage")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtlanguage)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.txtplant = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtplant.setObjectName("txtplant")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txtplant)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.txtlogin = QtWidgets.QLineEdit(self.formLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.txtlogin.setPalette(palette)
        self.txtlogin.setObjectName("txtlogin")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txtlogin)
        self.lblExiste = QtWidgets.QLabel(self.tab_6)
        self.lblExiste.setGeometry(QtCore.QRect(340, 250, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblExiste.setFont(font)
        self.lblExiste.setAcceptDrops(False)
        self.lblExiste.setAutoFillBackground(True)
        self.lblExiste.setFrameShape(QtWidgets.QFrame.Box)
        self.lblExiste.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblExiste.setText("")
        self.lblExiste.setObjectName("lblExiste")
        self.pbLast = QtWidgets.QPushButton(self.tab_6)
        self.pbLast.setGeometry(QtCore.QRect(590, 220, 81, 27))
        self.pbLast.setObjectName("pbLast")
        self.pbNext = QtWidgets.QPushButton(self.tab_6)
        self.pbNext.setGeometry(QtCore.QRect(500, 220, 81, 27))
        self.pbNext.setObjectName("pbNext")
        self.pbBack = QtWidgets.QPushButton(self.tab_6)
        self.pbBack.setGeometry(QtCore.QRect(420, 220, 81, 27))
        self.pbBack.setObjectName("pbBack")
        self.pbFirst = QtWidgets.QPushButton(self.tab_6)
        self.pbFirst.setGeometry(QtCore.QRect(330, 220, 81, 27))
        self.pbFirst.setObjectName("pbFirst")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_6)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(330, 0, 341, 211))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.txtlastName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtlastName.setObjectName("txtlastName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtlastName)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.txtfunction = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtfunction.setObjectName("txtfunction")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtfunction)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.txtemail = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtemail.setObjectName("txtemail")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtemail)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.txtsexo = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtsexo.setObjectName("txtsexo")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtsexo)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.txtdepartment = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtdepartment.setObjectName("txtdepartment")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txtdepartment)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.txtaliasUser = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtaliasUser.setObjectName("txtaliasUser")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txtaliasUser)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.txtdeparture = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtdeparture.setObjectName("txtdeparture")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.txtdeparture)
        self.txtname = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtname.setObjectName("txtname")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtname)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.pbUserExisted = QtWidgets.QPushButton(self.tab_6)
        self.pbUserExisted.setGeometry(QtCore.QRect(690, 230, 181, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbUserExisted.setFont(font)
        self.pbUserExisted.setObjectName("pbUserExisted")
        self.gbox2 = QtWidgets.QGroupBox(self.tab_6)
        self.gbox2.setGeometry(QtCore.QRect(690, 10, 151, 161))
        self.gbox2.setObjectName("gbox2")
        self.rbNew = QtWidgets.QRadioButton(self.gbox2)
        self.rbNew.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.rbNew.setObjectName("rbNew")
        self.rbUnlockUser = QtWidgets.QRadioButton(self.gbox2)
        self.rbUnlockUser.setGeometry(QtCore.QRect(10, 50, 101, 17))
        self.rbUnlockUser.setObjectName("rbUnlockUser")
        self.rbReplaceProfile = QtWidgets.QRadioButton(self.gbox2)
        self.rbReplaceProfile.setGeometry(QtCore.QRect(10, 80, 101, 17))
        self.rbReplaceProfile.setObjectName("rbReplaceProfile")
        self.rbExceptionalRequest = QtWidgets.QRadioButton(self.gbox2)
        self.rbExceptionalRequest.setGeometry(QtCore.QRect(10, 110, 131, 17))
        self.rbExceptionalRequest.setObjectName("rbExceptionalRequest")
        self.rbDeleteUser = QtWidgets.QRadioButton(self.gbox2)
        self.rbDeleteUser.setGeometry(QtCore.QRect(10, 140, 131, 17))
        self.rbDeleteUser.setObjectName("rbDeleteUser")
        self.pbUserExist = QtWidgets.QPushButton(self.tab_6)
        self.pbUserExist.setGeometry(QtCore.QRect(690, 190, 181, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbUserExist.setFont(font)
        self.pbUserExist.setObjectName("pbUserExist")
        self.cbTrip = QtWidgets.QCheckBox(self.tab_6)
        self.cbTrip.setGeometry(QtCore.QRect(700, 170, 70, 17))
        self.cbTrip.setObjectName("cbTrip")
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab_6)
        self.lcdNumber.setGeometry(QtCore.QRect(630, 420, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.txtrequestId_2 = QtWidgets.QLineEdit(self.tab_6)
        self.txtrequestId_2.setGeometry(QtCore.QRect(380, 490, 121, 31))
        self.txtrequestId_2.setObjectName("txtrequestId_2")
        self.label_68 = QtWidgets.QLabel(self.tab_6)
        self.label_68.setGeometry(QtCore.QRect(330, 490, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.pbProcurar = QtWidgets.QPushButton(self.tab_6)
        self.pbProcurar.setGeometry(QtCore.QRect(510, 490, 111, 31))
        self.pbProcurar.setObjectName("pbProcurar")
        self.pbLoadScreen = QtWidgets.QPushButton(self.tab_6)
        self.pbLoadScreen.setGeometry(QtCore.QRect(690, 460, 181, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbLoadScreen.setFont(font)
        self.pbLoadScreen.setObjectName("pbLoadScreen")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.widget = QtWidgets.QWidget(self.tab_7)
        self.widget.setGeometry(QtCore.QRect(0, 10, 371, 111))
        self.widget.setObjectName("widget")
        self.label_70 = QtWidgets.QLabel(self.widget)
        self.label_70.setGeometry(QtCore.QRect(10, 10, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.label_69 = QtWidgets.QLabel(self.widget)
        self.label_69.setGeometry(QtCore.QRect(10, 40, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.label_71 = QtWidgets.QLabel(self.widget)
        self.label_71.setGeometry(QtCore.QRect(10, 70, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.pBQuery01 = QtWidgets.QPushButton(self.widget)
        self.pBQuery01.setGeometry(QtCore.QRect(200, 10, 75, 23))
        self.pBQuery01.setObjectName("pBQuery01")
        self.pBQuery02 = QtWidgets.QPushButton(self.widget)
        self.pBQuery02.setGeometry(QtCore.QRect(200, 40, 75, 23))
        self.pBQuery02.setObjectName("pBQuery02")
        self.pBQuery03 = QtWidgets.QPushButton(self.widget)
        self.pBQuery03.setGeometry(QtCore.QRect(200, 70, 75, 23))
        self.pBQuery03.setObjectName("pBQuery03")
        self.txtQuery01 = QtWidgets.QLineEdit(self.widget)
        self.txtQuery01.setGeometry(QtCore.QRect(70, 10, 113, 20))
        self.txtQuery01.setObjectName("txtQuery01")
        self.txtQuery02 = QtWidgets.QLineEdit(self.widget)
        self.txtQuery02.setGeometry(QtCore.QRect(70, 40, 113, 20))
        self.txtQuery02.setObjectName("txtQuery02")
        self.txtQuery03 = QtWidgets.QLineEdit(self.widget)
        self.txtQuery03.setGeometry(QtCore.QRect(70, 70, 113, 20))
        self.txtQuery03.setObjectName("txtQuery03")
        self.pBQuery01_2 = QtWidgets.QPushButton(self.widget)
        self.pBQuery01_2.setGeometry(QtCore.QRect(280, 10, 75, 23))
        self.pBQuery01_2.setObjectName("pBQuery01_2")
        self.pBQuery02_2 = QtWidgets.QPushButton(self.widget)
        self.pBQuery02_2.setGeometry(QtCore.QRect(280, 40, 75, 23))
        self.pBQuery02_2.setObjectName("pBQuery02_2")
        self.pBQuery03_2 = QtWidgets.QPushButton(self.widget)
        self.pBQuery03_2.setGeometry(QtCore.QRect(280, 70, 75, 23))
        self.pBQuery03_2.setObjectName("pBQuery03_2")
        self.tabWidget_2.addTab(self.tab_7, "")

        self.retranslateUi(Form)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Criar Usuário no SAP"))
        self.pbCheckALLUser.setText(_translate("Form", "Check All Incompatibility per User"))
        self.pbInserirTexto.setText(_translate("Form", "Automático"))
        self.pbLoadingData.setText(_translate("Form", "01-Carregar Dados"))
        self.pbDownloadSAPUsers.setText(_translate("Form", "Download SAP Users"))
        self.pbValidateRecord.setText(_translate("Form", "Validar Registro"))
        self.pbCreateUser.setText(_translate("Form", "Criar usuário no SAP"))
        self.cbUserExisted.setText(_translate("Form", "Usuário já existiu?"))
        self.label_27.setText(_translate("Form", "Role 01"))
        self.label_28.setText(_translate("Form", "Role 02"))
        self.label_29.setText(_translate("Form", "Role 03"))
        self.label_30.setText(_translate("Form", "Role 04"))
        self.label_31.setText(_translate("Form", "Role 05"))
        self.label_32.setText(_translate("Form", "Role 06"))
        self.label_33.setText(_translate("Form", "Role 07"))
        self.label_34.setText(_translate("Form", "Role 08"))
        self.label_35.setText(_translate("Form", "Role 09"))
        self.label_36.setText(_translate("Form", "Role 10"))
        self.pbCK01.setText(_translate("Form", "CK"))
        self.pbCK02.setText(_translate("Form", "CK"))
        self.pbCK03.setText(_translate("Form", "CK"))
        self.pbCK04.setText(_translate("Form", "CK"))
        self.pbCK05.setText(_translate("Form", "CK"))
        self.pbCK06.setText(_translate("Form", "CK"))
        self.pbCK07.setText(_translate("Form", "CK"))
        self.pbCK08.setText(_translate("Form", "CK"))
        self.pbCK09.setText(_translate("Form", "CK"))
        self.pbCK10.setText(_translate("Form", "CK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.label_37.setText(_translate("Form", "Role 11"))
        self.label_38.setText(_translate("Form", "Role 12"))
        self.label_39.setText(_translate("Form", "Role 13"))
        self.label_40.setText(_translate("Form", "Role 14"))
        self.label_41.setText(_translate("Form", "Role 15"))
        self.label_42.setText(_translate("Form", "Role 16"))
        self.label_43.setText(_translate("Form", "Role 17"))
        self.label_44.setText(_translate("Form", "Role 18"))
        self.label_45.setText(_translate("Form", "Role 19"))
        self.label_46.setText(_translate("Form", "Role 20"))
        self.pbCK12.setText(_translate("Form", "CK"))
        self.pbCK13.setText(_translate("Form", "CK"))
        self.pbCK14.setText(_translate("Form", "CK"))
        self.pbCK15.setText(_translate("Form", "CK"))
        self.pbCK11.setText(_translate("Form", "CK"))
        self.pushButton_17.setText(_translate("Form", "CK"))
        self.pushButton_18.setText(_translate("Form", "CK"))
        self.pushButton_19.setText(_translate("Form", "CK"))
        self.pushButton_20.setText(_translate("Form", "CK"))
        self.pushButton_21.setText(_translate("Form", "CK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
        self.label_47.setText(_translate("Form", "Role 21"))
        self.label_48.setText(_translate("Form", "Role 22"))
        self.label_49.setText(_translate("Form", "Role 23"))
        self.label_50.setText(_translate("Form", "Role 24"))
        self.label_51.setText(_translate("Form", "Role 25"))
        self.label_52.setText(_translate("Form", "Role 26"))
        self.label_53.setText(_translate("Form", "Role 27"))
        self.label_54.setText(_translate("Form", "Role 28"))
        self.label_55.setText(_translate("Form", "Role 29"))
        self.label_56.setText(_translate("Form", "Role 30"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Tab 3"))
        self.label_57.setText(_translate("Form", "Role 31"))
        self.label_58.setText(_translate("Form", "Role 32"))
        self.label_59.setText(_translate("Form", "Role 33"))
        self.label_60.setText(_translate("Form", "Role 34"))
        self.label_61.setText(_translate("Form", "Role 35"))
        self.label_62.setText(_translate("Form", "Role 36"))
        self.label_63.setText(_translate("Form", "Role 37"))
        self.label_64.setText(_translate("Form", "Role 38"))
        self.label_65.setText(_translate("Form", "Role 39"))
        self.label_66.setText(_translate("Form", "Role 40"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Tab 4"))
        self.label_9.setText(_translate("Form", "Role 41"))
        self.label_18.setText(_translate("Form", "Role 42"))
        self.label_19.setText(_translate("Form", "Role 43"))
        self.label_20.setText(_translate("Form", "Role 44"))
        self.label_21.setText(_translate("Form", "Role 45"))
        self.label_22.setText(_translate("Form", "Role 46"))
        self.label_23.setText(_translate("Form", "Role 47"))
        self.label_24.setText(_translate("Form", "Role 48"))
        self.label_25.setText(_translate("Form", "Role 49"))
        self.label_26.setText(_translate("Form", "Role 50"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Tab 5"))
        self.pbExceptional2.setText(_translate("Form", "C3"))
        self.label_67.setText(_translate("Form", "ROLE Exceptional:"))
        self.pbExceptional1.setText(_translate("Form", "CK"))
        self.pbExceptional.setText(_translate("Form", "CK"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.rbN1.setText(_translate("Form", "N1"))
        self.rbN2.setText(_translate("Form", "N2"))
        self.rbN3.setText(_translate("Form", "N3"))
        self.rbN4.setText(_translate("Form", "N4"))
        self.rbN5.setText(_translate("Form", "N5"))
        self.label.setText(_translate("Form", "Request ID:"))
        self.label_2.setText(_translate("Form", "System Type:"))
        self.label_3.setText(_translate("Form", "System Env:"))
        self.label_4.setText(_translate("Form", "Group:"))
        self.label_5.setText(_translate("Form", "SNC Name:"))
        self.label_6.setText(_translate("Form", "Language:"))
        self.label_7.setText(_translate("Form", "Plant:"))
        self.label_8.setText(_translate("Form", "Login:"))
        self.pbLast.setText(_translate("Form", "Last"))
        self.pbNext.setText(_translate("Form", "Next"))
        self.pbBack.setText(_translate("Form", "Back"))
        self.pbFirst.setText(_translate("Form", "First"))
        self.label_11.setText(_translate("Form", "Sobrenome:"))
        self.label_12.setText(_translate("Form", "Função:"))
        self.label_13.setText(_translate("Form", "Email:"))
        self.label_14.setText(_translate("Form", "Sexo:"))
        self.label_15.setText(_translate("Form", "Department:"))
        self.label_16.setText(_translate("Form", "Alias user:"))
        self.label_17.setText(_translate("Form", "ED Departure:"))
        self.label_10.setText(_translate("Form", "Nome:"))
        self.pbUserExisted.setText(_translate("Form", "Usuário Existiu?"))
        self.gbox2.setTitle(_translate("Form", "GroupBox"))
        self.rbNew.setText(_translate("Form", "NEW"))
        self.rbUnlockUser.setText(_translate("Form", "Unlock User"))
        self.rbReplaceProfile.setText(_translate("Form", "Replace Profile"))
        self.rbExceptionalRequest.setText(_translate("Form", "Exceptional Request"))
        self.rbDeleteUser.setText(_translate("Form", "Delete User"))
        self.pbUserExist.setText(_translate("Form", "Usuário Existe?"))
        self.cbTrip.setText(_translate("Form", "TRIP ??"))
        self.label_68.setText(_translate("Form", "Ticket:"))
        self.pbProcurar.setText(_translate("Form", "Procurar"))
        self.pbLoadScreen.setText(_translate("Form", "02-Load Screen"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Form", "Tab 1"))
        self.label_70.setText(_translate("Form", "Query 01"))
        self.label_69.setText(_translate("Form", "Query 02"))
        self.label_71.setText(_translate("Form", "Query 03"))
        self.pBQuery01.setText(_translate("Form", "Standard"))
        self.pBQuery02.setText(_translate("Form", "Standard"))
        self.pBQuery03.setText(_translate("Form", "Standard"))
        self.pBQuery01_2.setText(_translate("Form", "Global"))
        self.pBQuery02_2.setText(_translate("Form", "Global"))
        self.pBQuery03_2.setText(_translate("Form", "Global"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("Form", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
